version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - gimel-net
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - gimel-net
    environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - gimel-net
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    networks:
      - gimel-net
    extra_hosts:
      - "moby:127.0.0.1"

  hbase-master:
    image: bde2020/hbase-master:latest
    container_name: hbase-master
    depends_on:
      - namenode
      - datanode
      - zookeeper
    env_file:
      - ./hbase-distributed-local.env
    networks:
      - gimel-net
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181"
    ports:
      - 16010:16010

  hbase-region:
    image: bde2020/hbase-regionserver:latest
    container_name: hbase-regionserver
    depends_on:
      - namenode
      - datanode
      - zookeeper
      - hbase-master
    env_file:
      - ./hbase-distributed-local.env
    networks:
      - gimel-net
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181 hbase-master:16010"
    ports:
      - 16030:16030

  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.7.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=gimel-quickstart
    ports:
      - "8020:8020"
    networks:
      - gimel-net
    env_file:
      - ./hadoop-hive.env

  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
    container_name: datanode
    depends_on:
      - namenode
    networks:
      - gimel-net
    env_file:
      - ./hadoop-hive.env

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.1.0
    container_name: hive-metastore-postgresql
    networks:
      - gimel-net

  hive-metastore:
    image: bde2020/hive:2.1.0-postgresql-metastore
    container_name: hive-metastore
    depends_on:
      - hive-metastore-postgresql
    env_file:
      - ./hadoop-hive.env
    command:
      - /opt/hive/bin/hive --service metastore
    networks:
      - gimel-net
    ports:
      - "9083:9083"

  hive-server:
    image: bde2020/hive:2.1.0-postgresql-metastore
    container_name: hive-server
    depends_on:
      - hive-metastore
      - hive-metastore-postgresql
    env_file:
      - ./hadoop-hive.env
    networks:
      - gimel-net
    environment:
      - "HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore"

  spark-master:
    image: bde2020/spark-master:2.2.0-hadoop2.7
    container_name: spark-master
    depends_on:
      - hive-metastore
      - hive-metastore-postgresql
      - hive-server
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    networks:
      - gimel-net
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
  spark-worker-1:
    image: bde2020/spark-worker:2.2.0-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - gimel-net
    environment:
     - "SPARK_MASTER=spark://spark-master:7077"
     - "constraint:node==spark-master"

networks:
  gimel-net:
