#!/bin/bash

export this_file=${0}
export this_script_path="$( cd "$( dirname "$this_file" )" && pwd)"
cd ${this_script_path}
cd ..
export UDC_HOME=${PWD}
source ${UDC_HOME}/build/udc_ui_functions
write_log "Current Working Directory is  ${UDC_HOME}"

export this_dir=`dirname $0`
source ${this_script_path}/set-env


write_log "------------------------------------------------------------------------------"
write_log "         Starting the UDC-UI DOCKER CONTAINER"
write_log "------------------------------------------------------------------------------"
run_cmd "docker-compose -f ${UDC_HOME}/quickstart/docker-compose-udc-ui-node.yml up -d" "ignore_errors"
check_error $? "docker-compose -f ${UDC_HOME}/quickstart/docker-compose-udc-ui-node.yml up -d"
