#!/bin/sh

export this_file=${0}
export this_script_path="$( cd "$( dirname "$this_file" )" && pwd)"
cd ${this_script_path}
cd ..
export UDC_HOME=${PWD}
source ${UDC_HOME}/build/udc_functions
write_log "Current Working Directory is  ${UDC_HOME}"

export this_dir=`dirname $0`
source ${this_script_path}/set-env

docker exec -i ${mysql_container_name} mysql -u${mysql_user} -p${mysql_password} ${mysql_database} < ${UDC_HOME}/quickstart/metastore/udc_ddl.sql
