# base image
FROM node:8.16.0

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm config set strict-ssl false
RUN npm install
RUN npm install -g @angular/cli@7.1.3

# add app
COPY . /app

# start app
CMD ng serve --host 0.0.0.0 --port 80
