#!/usr/bin/env bash

#set -x

export this_file=${0}
export this_script_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo ${this_script_path}
cd ${this_script_path}
cd ../
export GIMEL_HOME=${PWD}

#----------------------------function will write the message to Log File----------------------------#

#Usage : write_log < Whatever message you need to log >

write_log()
{

        msg=$1
        #echo $1
        #echo "" >> ${log_file}
        echo "$(date '+%Y%m%d %H:%M:%S') : $msg"
}

#----------------------------function will check for error code & exit if failure, else proceed further----------------------------#

#usage : Run immediately after executing any shell command - with 3 arguments.
#Example: check_error < pass $? from the shell command > < Error Code that you want the code to fail with > < Custom Message for errorcode -gt 0 >

check_error()
{

        cmd_error_code=$1
        pgm_exit_code=$2
        pgm_exit_msg=$3
        if  [ ${cmd_error_code} -gt 0 ]; then
                write_log "Error ! Exiting Program ... ${cmd_error_code} ${pgm_exit_code} ${pgm_exit_msg}"
                exit ${pgm_exit_code}
        else
                echo ""
        fi
}

write_log "Current Directory is --> ${PWD}"

write_log "Starting bootstrap for Gimel Data API"

sh $GIMEL_HOME/gimel-dataapi/gimel-quickstart/bootstrap.sh "$*"

write_log "SUCCESS !!!"