#!/bin/sh

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ -z $GIMEL_HOME ]; then
	export GIMEL_HOME=${PWD}
fi
export gimel_repo_home=${GIMEL_HOME}
export standalone_dir=${gimel_repo_home}/gimel-dataapi/gimel-standalone
export gimel_jar_name=gimel-sql-2.0.0-SNAPSHOT-uber.jar
export final_jar=${standalone_dir}/lib/$gimel_jar_name
export FLIGHTS_DATA_PATH=$GIMEL_HOME/gimel-dataapi/gimel-quickstart/flights
