#!/bin/sh

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

export this_file=${0}
export this_script_path="$( cd "$( dirname "$this_file" )" && pwd)"
cd ${this_script_path}
cd ..
export GIMEL_HOME=${PWD}
source ${GIMEL_HOME}/build/gimel_functions
write_log "Current Working Directory is  ${GIMEL_HOME}"
export this_dir=`dirname $0`
source ${this_script_path}/set-env

write_log "Stop if any container is running already"
run_cmd "sh $GIMEL_HOME/quickstart/stop-gimel stop"

mkdir ${GIMEL_HOME}/tmp ${GIMEL_HOME}/lib

write_log "Starting bootstrap for Gimel Data API"
run_cmd "sh $GIMEL_HOME/gimel-dataapi/gimel-quickstart/bootstrap.sh "$*""

write_log "SUCCESS !!!"
