#!/bin/sh

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

export docker_option=$1
if [ -z $docker_option ]; then
   docker_option="down"
fi
export this_file=${0}
export this_script_path=`dirname ${this_file}`
source $this_script_path/set-env
source ${GIMEL_HOME}/build/gimel_functions

cd ${GIMEL_HOME}/gimel-dataapi/gimel-standalone/docker
write_log "Current Directory is --> ${PWD}"
run_cmd "docker-compose $docker_option -t 30"

write_log "clearing the HDFS local data ..."
run_cmd "rm -rf {GIMEL_HOME}/gimel-dataapi/gimel-quickstart/__MAXOSX"

write_log "clearing the flights unzipped data..."
run_cmd "rm -rf {GIMEL_HOME}/gimel-dataapi/gimel-quickstart/flights"

write_log "clearing the directories ${GIMEL_HOME}/tmp ..."
run_cmd "rm -rf ${GIMEL_HOME}/tmp"

write_log "SUCCESS !!!"
